# vim: set ft=ruby :
vm_name = "gateway"
gateway_ip = "192.168.6.1"
private_ip = gateway_ip
netmask = "255.255.255.248"
cookbook_dir = "../chef-repo/cookbooks"
recipes = ["default-route", "router"]

Vagrant.configure(2) do |conf|
    conf.vm.box = "debian/stretch64"
    conf.vm.provider :virtualbox do |vb|
        vb.name = vm_name
    end

    conf.vm.define "gateway"
    conf.vm.hostname = "gateway"
    conf.vm.network "private_network", ip: private_ip, net_mask: netmask
    conf.vm.network "public_network"
    conf.vm.provision "chef_solo" do |chef|
        chef.cookbooks_path = cookbook_dir
        chef.json = {
            :route => {
                :ip_gateway => gateway_ip
            }
        }
        chef.add_recipe "apache2"
        recipes.each do |recipe|
            chef.add_recipe recipe
        end
    end
end
